name: flutter_unicamp
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_core_web: ^2.18.1
  cloud_firestore: ^5.5.0
  cloud_firestore_web: ^4.3.4
  firebase_storage: ^12.3.6
  font_awesome_flutter: ^10.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  provider: ^6.1.2
  firebase_ui_oauth_google: ^1.4.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  carousel_slider: ^5.0.0
  shared_preferences: ^2.3.3
  flutter_launcher_icons: ^0.14.1
  connectivity_plus: ^6.1.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets here
  assets:
    - assets/Main Page.jpg
    - assets/UniCampLogo.png
    - assets/UniCampAlt.png
    - assets/IconLogo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/IconLogo.png"
  adaptive_icon_background: "#ffffff"  # Optional white background
  adaptive_icon_foreground: "assets/IconLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true