// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxpIo95ZD-1m0ppIbPo6NY5Jt1L5GkpZk',
    appId: '1:227424076654:web:ca9b47204fa4959640777f',
    messagingSenderId: '227424076654',
    projectId: 'unicamp-ad6f4',
    authDomain: 'unicamp-ad6f4.firebaseapp.com',
    storageBucket: 'unicamp-ad6f4.firebasestorage.app',
    measurementId: 'G-LZYTVXZ1Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhpJPpB62l0aoQ3ZvR1eiaAQDTxCvRsfs',
    appId: '1:227424076654:android:8cf7a8e9c875b1a540777f',
    messagingSenderId: '227424076654',
    projectId: 'unicamp-ad6f4',
    storageBucket: 'unicamp-ad6f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhEdTNn9E5zsEOQ-dYQoa15b-1CxrJ03k',
    appId: '1:227424076654:ios:eb92326fd1aea99040777f',
    messagingSenderId: '227424076654',
    projectId: 'unicamp-ad6f4',
    storageBucket: 'unicamp-ad6f4.firebasestorage.app',
    androidClientId: '227424076654-a87qm6mk7tniocbmofaums71ar18fki1.apps.googleusercontent.com',
    iosClientId: '227424076654-1onnk8bf7avn22ad0u23eqv1nkdjvco4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUnicamp',
  );

}